### PR TITLE
Add ScalaJS support

### PR DESCRIPTION
**Pull request by sorenbug**
This has not been tested as the tests hang on my computer.

### CODE REVIEW

**Comment by sorenbug** [comment]
There seems to be issues with importing `fs2`, which is interesting, as the `build.sbt` is a near copy of the one from `scodec-core`, where dependencies import properly.

**Comment by sorenbug** [comment]
SBT thinks `project/[src]` is where the sources are supposed to go and not `./[src]`.

**Comment by sorenbug** [comment]
The ScalaJS tests fail to compile on my machine due to some sort of "export" thing but otherwise all of the sources compile properly

**Comment by mpilquist** [comment]
Scala.js support was added in a separate PR.

**Pull request closed without merging**
